# Project 1 Makefile
# Corey Johns
# COP4610 Spring 2013


CC = gcc47 -Wall -Wextra
CCO = $(CC) -o
CCC = $(CC) -c

myshell.x: myshell.o
	$(CCO) myshell.x myshell.o

myshell.o: myshell.c
	$(CCC) myshell.c
